<?php
class Telegro
{
    /**
     * @var Telegram's base api server url. Defaults to 'https://api.telegram.org/bot'.
     */
    public $base_url = "https://api.telegram.org/bot";
    /**
     * @var the bot token generated by Telegram.
     */
    private $bot_token;
    /**
     * @var the destination server to send request. Consists of the concatenation of the $base_url and the $bot_token.
     */
    private $server;

    /**
     * Set bot_token and server on object creation.
     * @param $bot_token. 
     * @return void.
     */
    public function __construct($bot_token)
    {
    	$this->bot_token = $bot_token;
        $this->setServer($this->base_url);
    }

    /**
     * Set server's url.
     * @param $base_url. 
     * @return void.
     */
    private function setServer($base_url)
    {
    	$this->server = $this->base_url . $this->bot_token;
    }

    /**
     * Change base url and reset the server.
     * @param $base_url. 
     * @return void.
     */
    public function setBaseUrl($base_url)
    {
    	$this->base_url = $base_url;
    	$this->setServer($base_url);
    }

    /**
     * Returns base url value.
     * @return $base_url.
     */
    public function getBaseUrl()
    {
        return $this->base_url;
    }

    /**
     * Set webhook.
     * @param $hook_url.
     * @return true | false.
     */
    public function setWebhook($hook_url)
    {
        return $this->execute([
            'method' => 'setwebhook',
            'values' => ['url' => $hook_url]
        ]);
    }

    /**
     * Get webhook information.
     * @return Object.
     */
    public function getWebhookInfo()
    {
        return $this->execute([
            'method' => 'getwebhookinfo',
        ]);
    }

    /**
     * Unset (Remove) webhook.
     * @return TRUE | FALSE.
     */
    public function unsetWebhook()
    {
        return $this->execute([
            'method' => 'setwebhook',
            'values' => ['url' => '']
        ]);
    } 

    /**
     * Get bot information.
     * @return Object.
     */
    public function getMe()
    {
        $result = $this->execute([
            'method' => 'getMe'
        ]);
        return json_decode($result);
    }

    /**
     * Get all messages have been received by bot.
     * @throws error. Conflict: can't use getUpdates method while webhook is active.
     * @return Object.
     */
    public function getUpdates()
    {
        $result = $this->execute([
            'method' => 'getUpdates'
        ]);
        return json_decode($result);
    }

    /**
     * Send text messages.
     * @param 
     * $options [ 
     *  chat_id => Unique identifier for the target chat or username of the target channel.
     *  text => Text of the message to be sent.
     *  parse_mode => Send Markdown or HTML, if you want Telegram apps to show bold, italic, fixed-width text or inline URLs in your bot's message.
     *  disable_web_page_preview => Disables link previews for links in this message. Defaults to false.
     *  disable_notification => Sends the message silently. Users will receive a notification with no sound. Defaults to false.
     *  reply_to_message_id => If the message is a reply, ID of the original message.
     *  reply_markup =>  A JSON-serialized object for an inline keyboard, custom reply keyboard, instructions to remove reply keyboard or to force a reply from the user.
     * ]
     * @throws error. chat_id can not be null.
     * @throws error. text can not be null.
     * @return Object.
     */
    public function sendMessage($options)
    {
        $default_options = [
            'chat_id' => null,
            'text' => '',
            'parse_mode' => '',
            'disable_web_page_preview' => false,
            'disable_notification' => false,
            'reply_to_message_id' => null,
            'reply_markup' => null,
        ];
        $options = array_merge($default_options, $options);

        //Throw exception if chat_id value is null.
        if (!$options['chat_id']) {
            throw new Exception("chat_id value could not be null.");
        }

        //Throw exception if text value is null.
        if (!$options['text']) {
            throw new Exception("text value could not be null.");
        }

        $result = $this->execute([
            'method' => 'sendMessage',
            'values' => $options
        ]);
        return json_decode($result);
    }

    /**
     * This method sends curl request to the server to run the given method and return curl response body.
     * @param 
     * $options [ 
     *  header => Could be any mime-type. Defaults to 'application/json'.
     *  ssl_verifier => Depends on the request need, could be TRUE or FALSE. Defaults to 'TRUE'.
     *  method => Could be any Telegram api method but not NULL.
     *  values => The method's parameters.
     * ]
     * @return response body.
     * @throws Exception if the method does not exist.
     */
    private function execute($options)
    {
        $default_options = [
            'header' => ['application/json'],
            'ssl_verifier' => true,
            'method' => null,
            'values' => [],
        ];
        $options = array_merge($default_options, $options);
        $request_url = "{$this->server}/{$options['method']}";

        //Throw exception if method value is null.
        if (!$options['method']) {
            throw new Exception("Method value could not be null.");
        }
        //Initialize curl to send request.
        $curl_handler = curl_init(); 
        curl_setopt($curl_handler, CURLOPT_HTTPHEADER, $options['header']);
        curl_setopt($curl_handler, CURLOPT_URL, $request_url); 
        curl_setopt($curl_handler, CURLOPT_RETURNTRANSFER, true); 
        curl_setopt($curl_handler, CURLOPT_HEADER, true);
        curl_setopt($curl_handler, CURLOPT_SSL_VERIFYPEER, $options['ssl_verifier']);
        curl_setopt($curl_handler, CURLOPT_POSTFIELDS, $options['values']); 
        $result = curl_exec($curl_handler);
        $header_size = curl_getinfo($curl_handler, CURLINFO_HEADER_SIZE);
        $header = substr($result, 0, $header_size);
        $body = substr($result, $header_size);
        curl_close($curl_handler);
        return $body;
    }
}
?>